name: Build and publish images
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish-nginx-rtmp-auth:
    runs-on: ubuntu-latest
    env:
      OWNER: numberoverzero
      PRODUCT: nginx
      SURFACE: rtmp
      COMPONENT: auth
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Configure meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.OWNER }}/${{ env.PRODUCT }}-${{ env.SURFACE }}-${{ env.COMPONENT }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
          labels: |
            n0.product=${{ env.PRODUCT }}
            n0.surface=${{ env.SURFACE }}
            n0.component=${{ env.COMPONENT }}
      -
        name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: nginx-rtmp-auth/Dockerfile
          context: ./nginx-rtmp-auth
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish-nginx-rtmp-server:
    runs-on: ubuntu-latest
    env:
      OWNER: numberoverzero
      PRODUCT: nginx
      SURFACE: rtmp
      COMPONENT: server
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Configure meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.OWNER }}/${{ env.PRODUCT }}-${{ env.SURFACE }}-${{ env.COMPONENT }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
          labels: |
            n0.product=${{ env.PRODUCT }}
            n0.surface=${{ env.SURFACE }}
            n0.component=${{ env.COMPONENT }}
      -
        name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: nginx-rtmp-server/Dockerfile
          context: ./nginx-rtmp-server
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}